services:
  # client:
  #   build:
  #     context: .
  #     dockerfile: DockerFileClient
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: dev
  #     NEXT_PUBLIC_API_URL: http://server:8080
  #   networks:
  #     - app-network

  server:
    build:
      context: .
      dockerfile: DockerFileServer
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://project_cms-db:3306/project_cms
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: p@ssw0rd
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      CLIENT_URL: localhost:3000
    networks:
      - app-network
  database:
    image: mysql:5.7
    container_name: project_cms-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_cms
      MYSQL_USER: user
      MYSQL_PASSWORD: p@ssw0rd
    volumes:
      - project_cms-db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  project_cms-db_data:

networks:
  app-network:
    driver: bridge
